---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: <ip>
      ansible_user: "centos"
      ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    vector-01:
      ansible_host: <ip>
      ansible_user: "centos"
      ansible_ssh_private_key_file: "~/.ssh/id_rsa"
